.PHONY: install test lint format run clean

install:
	@pip install -r requirements.txt

test:
	@pytest tests/

lint:
	@flake8 src/ tests/

format:
	@black src/ tests/

run:
	@python src/ingestion.py

clean:
	@find . -type f -name "*.pyc" -delete
	@find . -type d -name "__pycache__" -delete
